Repository jupyter-xeus/cpp-terminal, pull requests merged in 2022-05, with the labels that each got.

#164 Fix for undefined identifiers in platform.cpp
  cpp-terminal/private/inputOutputModeFlags.hpp
  cpp-terminal/private/platform.cpp
Labels: bug

#147 update readme
  .github/workflows/CI.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  README.md
  logo.svg
Labels: documentation

#142 Ported some fixes
  cpp-terminal/base.cpp
  cpp-terminal/base.hpp
  cpp-terminal/prompt.cpp
  examples/keys.cpp
  examples/kilo.cpp
  examples/menu.cpp
  examples/menu_window.cpp
  examples/menu_window_24bit.cpp
  examples/prompt_multiline.cpp
Labels: enhancement

#165 Supress undef ERROR
  cpp-terminal/private/platform.cpp
  cpp-terminal/private/platform.hpp
  cpp-terminal/prompt.hpp
Labels: enhancement

#171 Fixed a few smaller things
  cpp-terminal/CMakeLists.txt
  cpp-terminal/base.cpp
  cpp-terminal/base.hpp
  cpp-terminal/private/conversion.hpp
  cpp-terminal/private/inputOutputModeFlags.hpp
  cpp-terminal/private/platform.cpp
  cpp-terminal/prompt.hpp
  cpp-terminal/window.cpp
  cpp-terminal/window.hpp
  examples/keys.cpp
  examples/kilo.cpp
  examples/menu.cpp
  examples/menu_window.cpp
Labels: enhancement

#172 added functions for reading stdin
  .github/workflows/windows.yml
  .gitignore
  ci/compile_test.bat
  ci/compile_test.ps1
  ci/test.ps1
  ci/tests.sh
  cpp-terminal/input.cpp
  cpp-terminal/input.hpp
  cpp-terminal/private/platform.cpp
  cpp-terminal/private/platform.hpp
  examples/CMakeLists.txt
  examples/keys.cpp
  examples/kilo.cpp
  examples/menu.cpp
  examples/menu_window.cpp
  examples/menu_window_24bit.cpp
  examples/prompt_multiline.cpp
  examples/read_stdin.cpp
Labels: enhancement
